######################################################################
#
# File name : top_module_sim_compile.do
# Created on: Thu Jun 11 12:06:31 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib
vlib modelsim_lib/msim/xpm
vlib modelsim_lib/msim/blk_mem_gen_v8_4_2

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
vmap xpm modelsim_lib/msim/xpm
vmap blk_mem_gen_v8_4_2 modelsim_lib/msim/blk_mem_gen_v8_4_2

vlog -64 -incr -sv -work xil_defaultlib  \
"E:/vivado_1/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -64 -93 -work xpm  \
"E:/vivado_1/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -64 -incr -work blk_mem_gen_v8_4_2  \
"../../../../RIJ_CPU.ip_user_files/ipstatic/simulation/blk_mem_gen_v8_4.v" \

vlog -64 -incr -work xil_defaultlib  \
"../../../../RIJ_CPU.srcs/sources_1/ip/blk_mem_gen_0/sim/blk_mem_gen_0.v" \
"../../../../RIJ_CPU.srcs/sources_1/new/ALU_32.v" \
"../../../../RIJ_CPU.srcs/sources_1/new/Decoding_control.v" \
"../../../../RIJ_CPU.srcs/sources_1/new/PC_add.v" \
"../../../../RIJ_CPU.srcs/sources_1/new/RIJ_cpu.v" \
"../../../../RIJ_CPU.srcs/sources_1/new/mem_store.v" \
"../../../../RIJ_CPU.srcs/sources_1/new/register_store.v" \
"../../../../RIJ_CPU.srcs/sim_1/new/top_module_sim.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

