######################################################################
#
# File name : top_module_sim_wave.do
# Created on: Thu Jun 11 11:38:23 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
