######################################################################
#
# File name : top_module_sim_simulate.do
# Created on: Thu Jun 11 12:06:36 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L xpm -L blk_mem_gen_v8_4_2 -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.top_module_sim xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {top_module_sim_wave.do}

view wave
view structure
view signals

do {top_module_sim.udo}

run 1000ns
