# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/vivado_1/RIJ_CPU_/RIJ_CPU.cache/wt [current_project]
set_property parent.project_path E:/vivado_1/RIJ_CPU_/RIJ_CPU.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/vivado_1/RIJ_CPU_/RIJ_CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/vivado_1/RIJ_CPU_/register_mem.coe
add_files E:/vivado_1/RIJ_CPU_/mem_store.coe
add_files E:/vivado_1/RIJ_CPU_/register_mem_second.coe
read_verilog -library xil_defaultlib {
  E:/vivado_1/RIJ_CPU_/RIJ_CPU.srcs/sources_1/new/ALU_32.v
  E:/vivado_1/RIJ_CPU_/RIJ_CPU.srcs/sources_1/new/Decoding_control.v
  E:/vivado_1/RIJ_CPU_/RIJ_CPU.srcs/sources_1/new/PC_add.v
  E:/vivado_1/RIJ_CPU_/RIJ_CPU.srcs/sources_1/new/RIJ_cpu.v
  E:/vivado_1/RIJ_CPU_/RIJ_CPU.srcs/sources_1/new/mem_store.v
  E:/vivado_1/RIJ_CPU_/RIJ_CPU.srcs/sources_1/new/register_store.v
  E:/vivado_1/RIJ_CPU_/RIJ_CPU.srcs/sources_1/new/top_module.v
}
read_ip -quiet E:/vivado_1/RIJ_CPU_/RIJ_CPU.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/vivado_1/RIJ_CPU_/RIJ_CPU.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/vivado_1/RIJ_CPU_/RIJ_CPU.srcs/constrs_1/new/RIJ_constraints.xdc
set_property used_in_implementation false [get_files E:/vivado_1/RIJ_CPU_/RIJ_CPU.srcs/constrs_1/new/RIJ_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_module -part xc7a100tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
